def build_execute_auto_scan_deps(
    *,
    auto_scan_config,
    current_customer,
    get_last_scan_target,
    logger,
    network_key,
    rate_limiter,
    safe_emit,
    save_auto_scan_config,
    validate_target,
):
    return {
        "auto_scan_config": auto_scan_config,
        "current_customer": current_customer,
        "get_last_scan_target": get_last_scan_target,
        "logger": logger,
        "network_key": network_key,
        "rate_limiter": rate_limiter,
        "safe_emit": safe_emit,
        "save_auto_scan_config": save_auto_scan_config,
        "validate_target": validate_target,
    }


def build_scan_task_deps(
    *,
    broadcaster,
    emit_job_status,
    emit_to_client,
    ensure_job_not_cancelled,
    get_client_state,
    idle_state_manager,
    identify_gateway_firewall_targets,
    job_registry,
    logger,
    run_arp_scan,
    run_cancellable_command,
    socketio_sleep,
    update_job_progress,
    vulners_script,
):
    return {
        "broadcaster": broadcaster,
        "emit_to_client": emit_to_client,
        "get_client_state": get_client_state,
        "ensure_job_not_cancelled": ensure_job_not_cancelled,
        "idle_state_manager": idle_state_manager,
        "update_job_progress": update_job_progress,
        "socketio_sleep": socketio_sleep,
        "run_cancellable_command": run_cancellable_command,
        "run_arp_scan": run_arp_scan,
        "identify_gateway_firewall_targets": identify_gateway_firewall_targets,
        "job_registry": job_registry,
        "emit_job_status": emit_job_status,
        "logger": logger,
        "vulners_script": vulners_script,
    }


def build_report_task_deps(
    *,
    current_customer,
    customer_fingerprinter,
    emit_job_status,
    emit_to_client,
    extract_scan_statistics,
    get_app_version,
    get_client_state,
    idle_state_manager,
    job_registry,
    merge_nmap_xml_files,
    network_key,
    pdf_stylesheet,
    run_nmap_with_xml_output,
    sanitize_customer_dir_name,
    save_scan_metadata,
    scans_dir,
    socketio_sleep,
    split_subnet_into_chunks,
    stylesheet,
    update_job_progress,
    validate_target,
    web_stylesheet,
    convert_html_to_pdf,
    convert_xml_to_html,
    create_scan_folder,
):
    return {
        "job_registry": job_registry,
        "idle_state_manager": idle_state_manager,
        "emit_job_status": emit_job_status,
        "emit_to_client": emit_to_client,
        "update_job_progress": update_job_progress,
        "validate_target": validate_target,
        "split_subnet_into_chunks": split_subnet_into_chunks,
        "create_scan_folder": create_scan_folder,
        "scans_dir": scans_dir,
        "sanitize_customer_dir_name": sanitize_customer_dir_name,
        "run_nmap_with_xml_output": run_nmap_with_xml_output,
        "merge_nmap_xml_files": merge_nmap_xml_files,
        "socketio_sleep": socketio_sleep,
        "convert_xml_to_html": convert_xml_to_html,
        "convert_html_to_pdf": convert_html_to_pdf,
        "web_stylesheet": web_stylesheet,
        "pdf_stylesheet": pdf_stylesheet,
        "stylesheet": stylesheet,
        "get_app_version": get_app_version,
        "save_scan_metadata": save_scan_metadata,
        "get_client_state": get_client_state,
        "network_key": network_key,
        "current_customer": current_customer,
        "extract_scan_statistics": extract_scan_statistics,
        "customer_fingerprinter": customer_fingerprinter,
    }


def build_saved_pdf_task_deps(
    *,
    convert_html_to_pdf,
    convert_xml_to_html,
    emit_job_status,
    emit_to_client,
    find_latest_saved_scan_for_pdf,
    get_app_version,
    get_client_state,
    job_registry,
    logger,
    pdf_stylesheet,
    scans_dir,
    socketio_sleep,
    web_stylesheet,
):
    return {
        "job_registry": job_registry,
        "emit_job_status": emit_job_status,
        "emit_to_client": emit_to_client,
        "get_client_state": get_client_state,
        "find_latest_saved_scan_for_pdf": find_latest_saved_scan_for_pdf,
        "convert_xml_to_html": convert_xml_to_html,
        "convert_html_to_pdf": convert_html_to_pdf,
        "get_app_version": get_app_version,
        "logger": logger,
        "scans_dir": scans_dir,
        "socketio_sleep": socketio_sleep,
        "web_stylesheet": web_stylesheet,
        "pdf_stylesheet": pdf_stylesheet,
    }


def build_startup_check_deps(
    *,
    auto_scan_config,
    begin_startup_state,
    check_arp_scan,
    check_nmap,
    check_vulners,
    complete_startup_state,
    get_app_version,
    get_default_interface_cached,
    get_versions,
    load_auto_scan_config,
    load_current_assignment,
    logger,
    network_key,
    run_traceroute,
    safe_emit,
    startup_state,
    tool_versions,
    vulners_script,
):
    return {
        "begin_startup_state": begin_startup_state,
        "check_arp_scan": check_arp_scan,
        "check_nmap": check_nmap,
        "check_vulners": check_vulners,
        "complete_startup_state": complete_startup_state,
        "get_app_version": get_app_version,
        "get_default_interface_cached": get_default_interface_cached,
        "get_versions": get_versions,
        "load_auto_scan_config": load_auto_scan_config,
        "load_current_assignment": load_current_assignment,
        "logger": logger,
        "network_key": network_key,
        "run_traceroute": run_traceroute,
        "safe_emit": safe_emit,
        "startup_state": startup_state,
        "tool_versions": tool_versions,
        "auto_scan_config": auto_scan_config,
        "vulners_script": vulners_script,
    }
